// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/event_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/event_service.go -destination=internal/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/mohamedelhefni/siraaj/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
	isgomock struct{}
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// GetBrowsersDevicesOS mocks base method.
func (m *MockEventService) GetBrowsersDevicesOS(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrowsersDevicesOS", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrowsersDevicesOS indicates an expected call of GetBrowsersDevicesOS.
func (mr *MockEventServiceMockRecorder) GetBrowsersDevicesOS(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrowsersDevicesOS", reflect.TypeOf((*MockEventService)(nil).GetBrowsersDevicesOS), startDate, endDate, limit, filters)
}

// GetChannels mocks base method.
func (m *MockEventService) GetChannels(startDate, endDate time.Time, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannels", startDate, endDate, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannels indicates an expected call of GetChannels.
func (mr *MockEventServiceMockRecorder) GetChannels(startDate, endDate, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannels", reflect.TypeOf((*MockEventService)(nil).GetChannels), startDate, endDate, filters)
}

// GetEntryExitPages mocks base method.
func (m *MockEventService) GetEntryExitPages(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntryExitPages", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntryExitPages indicates an expected call of GetEntryExitPages.
func (mr *MockEventServiceMockRecorder) GetEntryExitPages(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntryExitPages", reflect.TypeOf((*MockEventService)(nil).GetEntryExitPages), startDate, endDate, limit, filters)
}

// GetEvents mocks base method.
func (m *MockEventService) GetEvents(query domain.EventQuery) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", query)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockEventServiceMockRecorder) GetEvents(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockEventService)(nil).GetEvents), query)
}

// GetFunnelAnalysis mocks base method.
func (m *MockEventService) GetFunnelAnalysis(request domain.FunnelRequest) (*domain.FunnelAnalysisResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFunnelAnalysis", request)
	ret0, _ := ret[0].(*domain.FunnelAnalysisResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFunnelAnalysis indicates an expected call of GetFunnelAnalysis.
func (mr *MockEventServiceMockRecorder) GetFunnelAnalysis(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunnelAnalysis", reflect.TypeOf((*MockEventService)(nil).GetFunnelAnalysis), request)
}

// GetOnlineUsers mocks base method.
func (m *MockEventService) GetOnlineUsers(timeWindow int, ownerID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnlineUsers", timeWindow, ownerID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnlineUsers indicates an expected call of GetOnlineUsers.
func (mr *MockEventServiceMockRecorder) GetOnlineUsers(timeWindow, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnlineUsers", reflect.TypeOf((*MockEventService)(nil).GetOnlineUsers), timeWindow, ownerID)
}

// GetStats mocks base method.
func (m *MockEventService) GetStats(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockEventServiceMockRecorder) GetStats(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockEventService)(nil).GetStats), startDate, endDate, limit, filters)
}

// GetTimeline mocks base method.
func (m *MockEventService) GetTimeline(startDate, endDate time.Time, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeline", startDate, endDate, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeline indicates an expected call of GetTimeline.
func (mr *MockEventServiceMockRecorder) GetTimeline(startDate, endDate, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeline", reflect.TypeOf((*MockEventService)(nil).GetTimeline), startDate, endDate, filters)
}

// GetTopCountries mocks base method.
func (m *MockEventService) GetTopCountries(startDate, endDate time.Time, limit int, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCountries", startDate, endDate, limit, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCountries indicates an expected call of GetTopCountries.
func (mr *MockEventServiceMockRecorder) GetTopCountries(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCountries", reflect.TypeOf((*MockEventService)(nil).GetTopCountries), startDate, endDate, limit, filters)
}

// GetTopEvents mocks base method.
func (m *MockEventService) GetTopEvents(startDate, endDate time.Time, limit int, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopEvents", startDate, endDate, limit, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopEvents indicates an expected call of GetTopEvents.
func (mr *MockEventServiceMockRecorder) GetTopEvents(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopEvents", reflect.TypeOf((*MockEventService)(nil).GetTopEvents), startDate, endDate, limit, filters)
}

// GetTopPages mocks base method.
func (m *MockEventService) GetTopPages(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopPages", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopPages indicates an expected call of GetTopPages.
func (mr *MockEventServiceMockRecorder) GetTopPages(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPages", reflect.TypeOf((*MockEventService)(nil).GetTopPages), startDate, endDate, limit, filters)
}

// GetTopSources mocks base method.
func (m *MockEventService) GetTopSources(startDate, endDate time.Time, limit int, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopSources", startDate, endDate, limit, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopSources indicates an expected call of GetTopSources.
func (mr *MockEventServiceMockRecorder) GetTopSources(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopSources", reflect.TypeOf((*MockEventService)(nil).GetTopSources), startDate, endDate, limit, filters)
}

// GetTopStats mocks base method.
func (m *MockEventService) GetTopStats(startDate, endDate time.Time, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopStats", startDate, endDate, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopStats indicates an expected call of GetTopStats.
func (mr *MockEventServiceMockRecorder) GetTopStats(startDate, endDate, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopStats", reflect.TypeOf((*MockEventService)(nil).GetTopStats), startDate, endDate, filters)
}

// TrackEvent mocks base method.
func (m *MockEventService) TrackEvent(event domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackEvent indicates an expected call of TrackEvent.
func (mr *MockEventServiceMockRecorder) TrackEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackEvent", reflect.TypeOf((*MockEventService)(nil).TrackEvent), event)
}

// TrackEventBatch mocks base method.
func (m *MockEventService) TrackEventBatch(events []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackEventBatch", events)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackEventBatch indicates an expected call of TrackEventBatch.
func (mr *MockEventServiceMockRecorder) TrackEventBatch(events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackEventBatch", reflect.TypeOf((*MockEventService)(nil).TrackEventBatch), events)
}
