// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/event_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/event_repository.go -destination=internal/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/mohamedelhefni/siraaj/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventRepository)(nil).Close))
}

// Create mocks base method.
func (m *MockEventRepository) Create(event domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEventRepositoryMockRecorder) Create(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepository)(nil).Create), event)
}

// CreateBatch mocks base method.
func (m *MockEventRepository) CreateBatch(events []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", events)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockEventRepositoryMockRecorder) CreateBatch(events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockEventRepository)(nil).CreateBatch), events)
}

// Flush mocks base method.
func (m *MockEventRepository) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockEventRepositoryMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockEventRepository)(nil).Flush))
}

// GetBrowsersDevicesOS mocks base method.
func (m *MockEventRepository) GetBrowsersDevicesOS(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrowsersDevicesOS", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrowsersDevicesOS indicates an expected call of GetBrowsersDevicesOS.
func (mr *MockEventRepositoryMockRecorder) GetBrowsersDevicesOS(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrowsersDevicesOS", reflect.TypeOf((*MockEventRepository)(nil).GetBrowsersDevicesOS), startDate, endDate, limit, filters)
}

// GetChannels mocks base method.
func (m *MockEventRepository) GetChannels(startDate, endDate time.Time, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannels", startDate, endDate, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannels indicates an expected call of GetChannels.
func (mr *MockEventRepositoryMockRecorder) GetChannels(startDate, endDate, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannels", reflect.TypeOf((*MockEventRepository)(nil).GetChannels), startDate, endDate, filters)
}

// GetEntryExitPages mocks base method.
func (m *MockEventRepository) GetEntryExitPages(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntryExitPages", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntryExitPages indicates an expected call of GetEntryExitPages.
func (mr *MockEventRepositoryMockRecorder) GetEntryExitPages(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntryExitPages", reflect.TypeOf((*MockEventRepository)(nil).GetEntryExitPages), startDate, endDate, limit, filters)
}

// GetEvents mocks base method.
func (m *MockEventRepository) GetEvents(query domain.EventQuery) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", query)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockEventRepositoryMockRecorder) GetEvents(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockEventRepository)(nil).GetEvents), query)
}

// GetFunnelAnalysis mocks base method.
func (m *MockEventRepository) GetFunnelAnalysis(request domain.FunnelRequest) (*domain.FunnelAnalysisResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFunnelAnalysis", request)
	ret0, _ := ret[0].(*domain.FunnelAnalysisResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFunnelAnalysis indicates an expected call of GetFunnelAnalysis.
func (mr *MockEventRepositoryMockRecorder) GetFunnelAnalysis(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunnelAnalysis", reflect.TypeOf((*MockEventRepository)(nil).GetFunnelAnalysis), request)
}

// GetOnlineUsers mocks base method.
func (m *MockEventRepository) GetOnlineUsers(timeWindow int, ownerID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnlineUsers", timeWindow, ownerID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnlineUsers indicates an expected call of GetOnlineUsers.
func (mr *MockEventRepositoryMockRecorder) GetOnlineUsers(timeWindow, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnlineUsers", reflect.TypeOf((*MockEventRepository)(nil).GetOnlineUsers), timeWindow, ownerID)
}

// GetStats mocks base method.
func (m *MockEventRepository) GetStats(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockEventRepositoryMockRecorder) GetStats(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockEventRepository)(nil).GetStats), startDate, endDate, limit, filters)
}

// GetTimeline mocks base method.
func (m *MockEventRepository) GetTimeline(startDate, endDate time.Time, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeline", startDate, endDate, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeline indicates an expected call of GetTimeline.
func (mr *MockEventRepositoryMockRecorder) GetTimeline(startDate, endDate, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeline", reflect.TypeOf((*MockEventRepository)(nil).GetTimeline), startDate, endDate, filters)
}

// GetTopCountries mocks base method.
func (m *MockEventRepository) GetTopCountries(startDate, endDate time.Time, limit int, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCountries", startDate, endDate, limit, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCountries indicates an expected call of GetTopCountries.
func (mr *MockEventRepositoryMockRecorder) GetTopCountries(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCountries", reflect.TypeOf((*MockEventRepository)(nil).GetTopCountries), startDate, endDate, limit, filters)
}

// GetTopEvents mocks base method.
func (m *MockEventRepository) GetTopEvents(startDate, endDate time.Time, limit int, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopEvents", startDate, endDate, limit, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopEvents indicates an expected call of GetTopEvents.
func (mr *MockEventRepositoryMockRecorder) GetTopEvents(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopEvents", reflect.TypeOf((*MockEventRepository)(nil).GetTopEvents), startDate, endDate, limit, filters)
}

// GetTopPages mocks base method.
func (m *MockEventRepository) GetTopPages(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopPages", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopPages indicates an expected call of GetTopPages.
func (mr *MockEventRepositoryMockRecorder) GetTopPages(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPages", reflect.TypeOf((*MockEventRepository)(nil).GetTopPages), startDate, endDate, limit, filters)
}

// GetTopSources mocks base method.
func (m *MockEventRepository) GetTopSources(startDate, endDate time.Time, limit int, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopSources", startDate, endDate, limit, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopSources indicates an expected call of GetTopSources.
func (mr *MockEventRepositoryMockRecorder) GetTopSources(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopSources", reflect.TypeOf((*MockEventRepository)(nil).GetTopSources), startDate, endDate, limit, filters)
}

// GetTopStats mocks base method.
func (m *MockEventRepository) GetTopStats(startDate, endDate time.Time, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopStats", startDate, endDate, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopStats indicates an expected call of GetTopStats.
func (mr *MockEventRepositoryMockRecorder) GetTopStats(startDate, endDate, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopStats", reflect.TypeOf((*MockEventRepository)(nil).GetTopStats), startDate, endDate, filters)
}
